#!/bin/bash

if [ -z "$2" ] || [ "$2" = "html" ]; then
    pandoc --standalone --from markdown --to html \
        -H assets/style.css \
        -o "docs/$1/index.html" "resume.$1.md"
    if [ ! $? -eq 0 ]; then
        exit 1
    fi
fi

if [ -z "$2" ] || [ "$2" = "pdf" ]; then
    pandoc --standalone --from markdown --to context \
        -V papersize=A4 \
        -o "docs/$1/resume.tex" "resume.$1.md"
    if [ ! $? -eq 0 ]; then
        exit 1
    fi

    cd "docs/$1" && context "resume.tex"
    if [ ! $? -eq 0 ]; then
        exit 1
    fi
    rm "resume.tex" "resume.tuc" "resume.log"
fi

